### ISSUE TITLE
`new_x` Parameter

### ISSUE THREAD

**Issue by prehner** [elrnv/ipopt-rs#10]
Hey there, thank you for this crate. I think it provides a very well designed and "rusty" interface to the IPOPT solver.

I am just wondering: is there a particular reason why you skip the `new_x` parameter in the Rust interface? I have a complex NLP that basically solves objective and constraint values simultaneously, so for performance reasons it would be useful to cache the results.

**Comment by elrnv** [comment]
Thank you for the question! I may not be remembering my reason right, but I believe I made this decision to simplify the interface, since IIRC this type of caching can be implemented on the client side. But if there is a good case to add it to the API, I am happy to accept a PR for this!

**Comment by prehner** [comment]
Great! I'll have a look how messy caching objectives and constraints manually would be (which would happen outside this crate anyways) and push a PR if the solution makes sense.

**Comment by elrnv** [comment]
Fixed by #11
