### ISSUE TITLE
Caching in BasicProblem and ConstrainedProblem methods

### ISSUE THREAD

**Issue by paul-scott** [elrnv/ipopt-rs#5]
One issue I'm having interfacing Descent is that I make use of caching calculations between the various ipopt callbacks. It is more efficient to calculate some of the quantities at the same time rather than separately. Basically I check `new_x` in each relevant function to see if it is the first time I've seen that value (for this iteration). The `BasicProblem` and `ConstrainedProblem` traits don't allow passing of `new_x`.
I was wondering if you have any advice on progressing with this. We could change the traits to include passing on `new_x`, or it is might be possible to create a new Trait that does specifically this, but then it won't be compatible with `Ipopt<P: BasicProblem>`.

**Comment by elrnv** [comment]
I remember intentionally ignoring the `new_x` parameter because the Ipopt documentation mentioned they did caching internally:

> The boolean variable new_x will be false if the last call to any of the evaluation methods (eval_*) used the same $ x$ values. This can be helpful when users have efficient implementations that calculate multiple outputs at once. IPOPT internally caches results from the TNLP and generally, this flag can be ignored. 

But reading that again I think I get why it's actually useful. The gist of it (please correct me if I'm wrong) is that the caller can precompute the values for several `eval_*` functions in a single say `eval_f`, and just reuse these results when the appropriate `eval_*` function is actually called instead of recomputing the result.

Adding this to the existing interface totally makes sense to me.

There is a corresponding [issue in Ipopt.jl](https://github.com/JuliaOpt/Ipopt.jl/issues/34) (Julia bindings to Ipopt) in which it's recommended to do this manually by storing `x`, but I think it makes sense to expose this piece of information in the callbacks directly.

**Comment by elrnv** [comment]
I think this can be represented cleanly by wrapping the x input in an enum, which will tie this flag directly to `x`. Something like this:

```rust
enum Input<'a> {
    Old(&'a [Number]),
    New(&'a [Number]),
}
```

Then the callback will look something like:

```rust
fn objective(&self, x: Input<'_>, obj: &mut Number) -> bool;
```

To make this all work seamlessly with existing code, requiring only the change to the function call we should probably have a `Deref<[Number]>` impl for `Input<'_>`.

What do you think?

**Comment by elrnv** [comment]
Just to throw some other suggestions for the enum variants, we could have Stale/Fresh, Clean/Dirty, Seen/New. For the enum name itself, maybe `Var`.

**Comment by paul-scott** [comment]
Maybe the approach suggested in that Julia is acceptable performance-wise, I should run a test.
It is basically 5 x n extra comparisons vs 5 comparisons. It is curious that the ipopt interface decided to expose new_x and new_lambda if just performing these comparisons yourself is negligible / stable, but maybe it was just for convenience.

Assuming it is something worth pursuing, the approach you suggest makes sense to me. My feeling is that the Seen / New combination is most informative.

**Comment by elrnv** [comment]
If you do get a chance to run a benchmark, it would be very helpful to have it pasted here for reference. I suspect the performance benefit may be noticeable in large problems with simple Hessians...

**Comment by paul-scott** [comment]
I've finally got around to constructing some benchmarks for the problem I'm interested in, and testing with new_x vs checking for equality of a copied version of x. The difference is insignificant (in the noise so not worth pasting here).

By no means is this comprehensive and maybe for some problems with simple Hessians as you suggest it may make a difference, but for my purposes I'm happy to continue to integrate with the current api as is. Go ahead and close this if you like.

**Comment by elrnv** [comment]
Awesome! Thanks for the confirmation. Closing this for now. May come back if more demand arises.
